Update tests for ccpp diagnostics line info

diff --git a/code/Makefile b/code/Makefile
--- a/code/Makefile
+++ b/code/Makefile
@@ -213,7 +213,7 @@ test: *.nc
 	echo "neo-c ../code6/c_test_compat64_error_active.nc (expect diagnostic)"; \
 	rm -f c_test_compat64_error_active; \
 	$(NEO_C) -I. ../code6/c_test_compat64_error_active.nc -o c_test_compat64_error_active > c_test_compat64_error_active.out 2>&1 || true; \
-	grep -q "error:" c_test_compat64_error_active.out; \
+	grep -Eqi "(\\[error\\]|error:)" c_test_compat64_error_active.out; \
 	test ! -e c_test_compat64_error_active; \
 	rm -f c_test_compat64_error_active.out
 	@set -eu; \
@@ -236,7 +236,7 @@ test: *.nc
 	echo "neo-c ../code6/c_test_compat65_negative_array.nc (expect diagnostic)"; \
 	rm -f c_test_compat65_negative_array; \
 	$(NEO_C) -I. ../code6/c_test_compat65_negative_array.nc -o c_test_compat65_negative_array > c_test_compat65_negative_array.out 2>&1 || true; \
-	grep -qi "error:" c_test_compat65_negative_array.out; \
+	grep -Eqi "(\\[error\\]|error:)" c_test_compat65_negative_array.out; \
 	test ! -e c_test_compat65_negative_array; \
 	rm -f c_test_compat65_negative_array.out
 	$(NEO_C) -I. ../code6/c_test_compat66.nc -o c_test_compat66
@@ -636,7 +636,7 @@ test: *.nc
 	echo "neo-c ../code6/c_test_compat142.nc (expect diagnostic)"; \
 	rm -f c_test_compat142; \
 	$(NEO_C) -I. ../code6/c_test_compat142.nc -o c_test_compat142 > c_test_compat142.out 2>&1 || true; \
-	grep -qi "^error:" c_test_compat142.out; \
+	grep -Eqi "(\\[error\\]|^error:)" c_test_compat142.out; \
 	test ! -e c_test_compat142; \
 	rm -f c_test_compat142.out
 	$(NEO_C) -I. ../code6/c_test_compat143.nc -o c_test_compat143
@@ -1010,6 +1010,30 @@ test: *.nc
 	./c_test_compat249
 	$(NEO_C) -I. ../code6/c_test_compat250.nc -o c_test_compat250
 	./c_test_compat250
+	@set -eu; \
+	echo "neo-c ../code6/c_test_compat251.nc (expect warning with line info)"; \
+	rm -f c_test_compat251; \
+	$(NEO_C) -I. ../code6/c_test_compat251.nc -o c_test_compat251 > c_test_compat251.out 2>&1 || true; \
+	grep -Eq "c_test_compat251\\.nc 2\\(2\\): \\[warning\\] ccpp-warning-line-check" c_test_compat251.out; \
+	test -e c_test_compat251; \
+	./c_test_compat251; \
+	rm -f c_test_compat251.out
+	@set -eu; \
+	echo "neo-c ../code6/c_test_compat252.nc (expect diagnostic)"; \
+	rm -f c_test_compat252; \
+	$(NEO_C) -I. ../code6/c_test_compat252.nc -o c_test_compat252 > c_test_compat252.out 2>&1 || true; \
+	grep -Eq "c_test_compat252\\.nc 2\\(2\\): \\[error\\] ccpp-error-line-check" c_test_compat252.out; \
+	test ! -e c_test_compat252; \
+	! grep -q "^error:" c_test_compat252.out; \
+	rm -f c_test_compat252.out
+	@set -eu; \
+	echo "neo-c ../code6/c_test_compat253.nc (expect diagnostic)"; \
+	rm -f c_test_compat253; \
+	$(NEO_C) -I. ../code6/c_test_compat253.nc -o c_test_compat253 > c_test_compat253.out 2>&1 || true; \
+	grep -Eq "c_test_compat253\\.nc 700\\(700\\): \\[error\\] ccpp-error-line-directive-check" c_test_compat253.out; \
+	test ! -e c_test_compat253; \
+	! grep -q "^error:" c_test_compat253.out; \
+	rm -f c_test_compat253.out
 	$(NEO_C) test_control_flow.nc
 	./test_control_flow
 	$(NEO_C) test_control.nc
@@ -1042,5 +1066,5 @@ test: *.nc
 clean:
 	rm -rf test_array_features test_array_pointer_advanced test_typedefs test_array_pointer_matrix test_array_views test_pointer_qualifiers test_comelang test_comelang2 test_comelang3 test_nums inline_asm c_test_compat39 c_test_compat40 c_test_compat41 c_test_compat42 c_test_compat43 c_test_compat44 c_test_compat45 c_test_compat46 c_test_compat47 c_test_compat48 c_test_compat49 c_test_compat50 c_test_compat51 c_test_compat52 c_test_compat53 c_test_compat54 c_test_compat55
 	rm -rf *.c .*.bin runner .valid_bin .invalid_bin .test_out *.nc.nc *.nc.o ./attrs ./codex ./neo-c ./neo-c10 ./neo-c11 ./neo-c12 ./neo-c13 ./neo-c14 ./neo-c2 ./neo-c3 ./neo-c4 ./neo-c5 ./neo-c6 ./neo-c7 ./neo-c8 ./neo-c9 ./labels_as_values ./nested_functions ./statement_expr ./test_arith ./test_array_ptr ./test_c_compat ./test_c_compat2 ./test_c_compat3 ./test_c_compat4 ./test_c_compat5 ./test_c_compat6 ./test_c_compat7 ./c_test_compat8 ./c_test_compat9 ./c_test_compat38 ./c_test_compat39 ./c_test_compat40 ./c_test_compat41 ./c_test_compat42 ./c_test_compat43 ./c_test_compat44 ./c_test_compat45 ./c_test_compat46 ./c_test_compat47 ./c_test_compat48 ./c_test_compat49 ./c_test_compat50 ./c_test_compat51 ./c_test_compat52 ./c_test_compat53 ./c_test_compat54 ./c_test_compat55 ./c_test_compat10 ./c_test_compat11 ./c_test_compat12 ./c_test_compat13 ./c_test_compat14 ./c_test_compat15 ./c_test_compat16 ./c_test_compat17 ./c_test_compat18 ./c_test_compat19 ./c_test_compat20 ./c_test_compat21 ./c_test_compat22 ./c_test_compat23 ./c_test_compat24 ./c_test_compat25 ./c_test_compat26 ./c_test_compat27 ./c_test_compat28 ./c_test_compat29 ./c_test_compat30 ./c_test_compat31 ./c_test_compat32 ./c_test_compat33 ./c_test_compat34 ./c_test_compat35 ./c_test_compat36 ./c_test_compat37 ./test_control_flow ./test_control ./test_functions ./test_invalid_0888 ./test_ops ./test_pointers_arrays ./test_string_cast ./test_struct_enum ./test_struct_union_enum ./test_switch_ternary ./test_valid *.i* *.nc.nc* ./attrs ./builtins ./codex ./comelang ./comelang10 ./comelang11 ./comelang12 ./comelang13 ./comelang14 ./comelang2 ./comelang3 ./comelang4 ./comelang5 ./comelang6 ./comelang7 ./comelang8 ./comelang9 ./labels_as_values ./nested_functions ./runner ./statement_expr ./test_arith ./test_array_ptr ./test_c_compat ./test_c_compat2 ./test_c_compat3 ./test_c_compat4 ./test_c_compat5 ./test_c_compat6 ./test_c_compat7 ./c_test_compat8 ./c_test_compat9 ./c_test_compat10 ./c_test_compat11 ./c_test_compat12 ./c_test_compat13 ./c_test_compat14 ./c_test_compat15 ./c_test_compat16 ./c_test_compat17 ./c_test_compat18 ./c_test_compat19 ./c_test_compat20 ./c_test_compat21 ./c_test_compat22 ./c_test_compat23 ./c_test_compat24 ./c_test_compat25 ./c_test_compat26 ./c_test_compat27 ./c_test_compat28 ./c_test_compat29 ./c_test_compat30 ./c_test_compat31 ./c_test_compat32 ./c_test_compat33 ./c_test_compat34 ./c_test_compat35 ./c_test_compat36 ./c_test_compat37 ./c_test_compat39 ./c_test_compat40 ./c_test_compat41 ./c_test_compat42 ./c_test_compat43 ./c_test_compat44 ./c_test_compat45 ./c_test_compat46 ./c_test_compat47 ./c_test_compat48 ./c_test_compat49 ./c_test_compat50 ./c_test_compat51 ./c_test_compat52 ./c_test_compat53 ./c_test_compat54 ./c_test_compat55 ./test_control_flow ./test_control ./test_functions ./test_invalid_0888 ./test_ops ./test_pointers_arrays ./test_string_cast ./test_struct_enum ./test_struct_union_enum ./test_switch_ternary ./test_valid ./typeof_auto ./user ./vector_types test_c_compat_host test_c_compat2_host test_c_compat3_host test_c_compat4_host test_c_compat5_host test_c_compat6_host test_c_compat7_host c_test_compat8_host c_test_compat9_host c_test_compat10_host c_test_compat11_host c_test_compat12_host c_test_compat13_host c_test_compat14_host c_test_compat15_host c_test_compat16_host c_test_compat17_host c_test_compat18_host c_test_compat19_host c_test_compat20_host c_test_compat21_host c_test_compat22_host c_test_compat23_host c_test_compat24_host c_test_compat25_host c_test_compat26_host c_test_compat27_host c_test_compat28_host c_test_compat29_host c_test_compat30_host c_test_compat31_host c_test_compat32_host c_test_compat33_host c_test_compat34_host c_test_compat35_host c_test_compat36_host c_test_compat37_host c_test_compat42_host c_test_compat43_host c_test_compat44_host c_test_compat45_host c_test_compat46_host c_test_compat47_host c_test_compat48_host c_test_compat49_host c_test_compat50_host c_test_compat51_host c_test_compat52_host c_test_compat53_host c_test_compat54_host c_test_compat55_host
-	rm -rf ./c_test_compat56 ./c_test_compat57 ./c_test_compat58 ./c_test_compat59 ./c_test_compat60 ./c_test_compat61 ./c_test_compat62 ./c_test_compat63 ./c_test_compat64 ./c_test_compat65 ./c_test_compat66 ./c_test_compat67 ./c_test_compat68 ./c_test_compat69 ./c_test_compat70 ./c_test_compat71 ./c_test_compat72 ./c_test_compat73 ./c_test_compat74 ./c_test_compat75 ./c_test_compat76 ./c_test_compat77 ./c_test_compat78 ./c_test_compat79 ./c_test_compat80 ./c_test_compat81 ./c_test_compat82 ./c_test_compat83 ./c_test_compat84 ./c_test_compat85 ./c_test_compat86 ./c_test_compat87 ./c_test_compat88 ./c_test_compat89 ./c_test_compat90 ./c_test_compat91 ./c_test_compat92 ./c_test_compat93 ./c_test_compat94 ./c_test_compat95 ./c_test_compat96 ./c_test_compat97 ./c_test_compat98 ./c_test_compat99 ./c_test_compat100 ./c_test_compat101 ./c_test_compat102 ./c_test_compat103 ./c_test_compat104 ./c_test_compat105 ./c_test_compat106 ./c_test_compat107 ./c_test_compat108 ./c_test_compat109 ./c_test_compat110 ./c_test_compat111 ./c_test_compat112 ./c_test_compat113 ./c_test_compat114 ./c_test_compat115 ./c_test_compat116 ./c_test_compat117 ./c_test_compat118 ./c_test_compat119 ./c_test_compat120 ./c_test_compat121 ./c_test_compat122 ./c_test_compat123 ./c_test_compat124 ./c_test_compat125 ./c_test_compat126 ./c_test_compat127 ./c_test_compat128 ./c_test_compat129 ./c_test_compat130 ./c_test_compat131 ./c_test_compat132 ./c_test_compat133 ./c_test_compat134 ./c_test_compat135 ./c_test_compat136 ./c_test_compat137 ./c_test_compat138 ./c_test_compat139 ./c_test_compat140 ./c_test_compat141 ./c_test_compat142 ./c_test_compat143 ./c_test_compat144 ./c_test_compat145 ./c_test_compat146 ./c_test_compat147 ./c_test_compat148 ./c_test_compat149 ./c_test_compat150 ./c_test_compat151 ./c_test_compat152 ./c_test_compat153 ./c_test_compat154 ./c_test_compat155 ./c_test_compat156 ./c_test_compat157 ./c_test_compat158 ./c_test_compat159 ./c_test_compat160 ./c_test_compat161 ./c_test_compat162 ./c_test_compat163 ./c_test_compat164 ./c_test_compat165 ./c_test_compat166 ./c_test_compat167 ./c_test_compat168 ./c_test_compat169 ./c_test_compat170 ./c_test_compat171 ./c_test_compat172 ./c_test_compat173 ./c_test_compat174 ./c_test_compat175 ./c_test_compat176 ./c_test_compat177 ./c_test_compat178 ./c_test_compat179 ./c_test_compat180 ./c_test_compat181 ./c_test_compat182 ./c_test_compat183 ./c_test_compat184 ./c_test_compat185 ./c_test_compat186 ./c_test_compat187 ./c_test_compat188 ./c_test_compat189 ./c_test_compat190 ./c_test_compat191 ./c_test_compat192 ./c_test_compat193 ./c_test_compat194 ./c_test_compat195 ./c_test_compat196 ./c_test_compat197 ./c_test_compat198 ./c_test_compat199 ./c_test_compat200 ./c_test_compat201 ./c_test_compat202 ./c_test_compat203 ./c_test_compat204 ./c_test_compat205 ./c_test_compat206 ./c_test_compat207 ./c_test_compat208 ./c_test_compat209 ./c_test_compat210 ./c_test_compat211 ./c_test_compat212 ./c_test_compat213 ./c_test_compat214 ./c_test_compat215 ./c_test_compat216 ./c_test_compat217 ./c_test_compat218 ./c_test_compat219 ./c_test_compat220 ./c_test_compat221 ./c_test_compat222 ./c_test_compat223 ./c_test_compat224 ./c_test_compat225 ./c_test_compat226 ./c_test_compat227 ./c_test_compat228 ./c_test_compat229 ./c_test_compat230 ./c_test_compat231 ./c_test_compat232 ./c_test_compat233 ./c_test_compat234 ./c_test_compat235 ./c_test_compat236 ./c_test_compat237 ./c_test_compat238 ./c_test_compat239 ./c_test_compat240 ./c_test_compat241 ./c_test_compat242 ./c_test_compat243 ./c_test_compat244 ./c_test_compat245 ./c_test_compat246 ./c_test_compat247 ./c_test_compat248 ./c_test_compat249 ./c_test_compat250
+	rm -rf ./c_test_compat56 ./c_test_compat57 ./c_test_compat58 ./c_test_compat59 ./c_test_compat60 ./c_test_compat61 ./c_test_compat62 ./c_test_compat63 ./c_test_compat64 ./c_test_compat65 ./c_test_compat66 ./c_test_compat67 ./c_test_compat68 ./c_test_compat69 ./c_test_compat70 ./c_test_compat71 ./c_test_compat72 ./c_test_compat73 ./c_test_compat74 ./c_test_compat75 ./c_test_compat76 ./c_test_compat77 ./c_test_compat78 ./c_test_compat79 ./c_test_compat80 ./c_test_compat81 ./c_test_compat82 ./c_test_compat83 ./c_test_compat84 ./c_test_compat85 ./c_test_compat86 ./c_test_compat87 ./c_test_compat88 ./c_test_compat89 ./c_test_compat90 ./c_test_compat91 ./c_test_compat92 ./c_test_compat93 ./c_test_compat94 ./c_test_compat95 ./c_test_compat96 ./c_test_compat97 ./c_test_compat98 ./c_test_compat99 ./c_test_compat100 ./c_test_compat101 ./c_test_compat102 ./c_test_compat103 ./c_test_compat104 ./c_test_compat105 ./c_test_compat106 ./c_test_compat107 ./c_test_compat108 ./c_test_compat109 ./c_test_compat110 ./c_test_compat111 ./c_test_compat112 ./c_test_compat113 ./c_test_compat114 ./c_test_compat115 ./c_test_compat116 ./c_test_compat117 ./c_test_compat118 ./c_test_compat119 ./c_test_compat120 ./c_test_compat121 ./c_test_compat122 ./c_test_compat123 ./c_test_compat124 ./c_test_compat125 ./c_test_compat126 ./c_test_compat127 ./c_test_compat128 ./c_test_compat129 ./c_test_compat130 ./c_test_compat131 ./c_test_compat132 ./c_test_compat133 ./c_test_compat134 ./c_test_compat135 ./c_test_compat136 ./c_test_compat137 ./c_test_compat138 ./c_test_compat139 ./c_test_compat140 ./c_test_compat141 ./c_test_compat142 ./c_test_compat143 ./c_test_compat144 ./c_test_compat145 ./c_test_compat146 ./c_test_compat147 ./c_test_compat148 ./c_test_compat149 ./c_test_compat150 ./c_test_compat151 ./c_test_compat152 ./c_test_compat153 ./c_test_compat154 ./c_test_compat155 ./c_test_compat156 ./c_test_compat157 ./c_test_compat158 ./c_test_compat159 ./c_test_compat160 ./c_test_compat161 ./c_test_compat162 ./c_test_compat163 ./c_test_compat164 ./c_test_compat165 ./c_test_compat166 ./c_test_compat167 ./c_test_compat168 ./c_test_compat169 ./c_test_compat170 ./c_test_compat171 ./c_test_compat172 ./c_test_compat173 ./c_test_compat174 ./c_test_compat175 ./c_test_compat176 ./c_test_compat177 ./c_test_compat178 ./c_test_compat179 ./c_test_compat180 ./c_test_compat181 ./c_test_compat182 ./c_test_compat183 ./c_test_compat184 ./c_test_compat185 ./c_test_compat186 ./c_test_compat187 ./c_test_compat188 ./c_test_compat189 ./c_test_compat190 ./c_test_compat191 ./c_test_compat192 ./c_test_compat193 ./c_test_compat194 ./c_test_compat195 ./c_test_compat196 ./c_test_compat197 ./c_test_compat198 ./c_test_compat199 ./c_test_compat200 ./c_test_compat201 ./c_test_compat202 ./c_test_compat203 ./c_test_compat204 ./c_test_compat205 ./c_test_compat206 ./c_test_compat207 ./c_test_compat208 ./c_test_compat209 ./c_test_compat210 ./c_test_compat211 ./c_test_compat212 ./c_test_compat213 ./c_test_compat214 ./c_test_compat215 ./c_test_compat216 ./c_test_compat217 ./c_test_compat218 ./c_test_compat219 ./c_test_compat220 ./c_test_compat221 ./c_test_compat222 ./c_test_compat223 ./c_test_compat224 ./c_test_compat225 ./c_test_compat226 ./c_test_compat227 ./c_test_compat228 ./c_test_compat229 ./c_test_compat230 ./c_test_compat231 ./c_test_compat232 ./c_test_compat233 ./c_test_compat234 ./c_test_compat235 ./c_test_compat236 ./c_test_compat237 ./c_test_compat238 ./c_test_compat239 ./c_test_compat240 ./c_test_compat241 ./c_test_compat242 ./c_test_compat243 ./c_test_compat244 ./c_test_compat245 ./c_test_compat246 ./c_test_compat247 ./c_test_compat248 ./c_test_compat249 ./c_test_compat250 ./c_test_compat251 ./c_test_compat252 ./c_test_compat253
 	rm -rf ./reports/external_corpus
